<div>
    @if($successMessage)<div class="flash-message" role="status"><span>{{ $successMessage }}</span><button type="button" wire:click="$set('successMessage', '')" aria-label="Fechar mensagem">×</button></div>@endif
    <header class="dashboard-heading"><div><p class="eyebrow">PLANEJAMENTO</p><h1>Orçamentos e metas</h1><p>Transforme seus planos em números acompanháveis.</p></div><a wire:navigate href="{{ route('dashboard') }}" class="btn-secondary">← Dashboard</a></header>

    <section class="accounts-tabs">
        <div class="tabs-list" role="tablist" aria-label="Planejamento financeiro"><button type="button" role="tab" wire:click="$set('activeTab', 'budgets')" @class(['tab-button', 'is-active' => $activeTab === 'budgets'])>Orçamentos</button><button type="button" role="tab" wire:click="$set('activeTab', 'goals')" @class(['tab-button', 'is-active' => $activeTab === 'goals'])>Metas</button></div>

        @if($activeTab === 'budgets')
            <div class="tab-panel"><div class="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-semibold text-slate-900">Orçamentos de {{ now()->translatedFormat('F') }}</h2><p class="mt-1 text-sm text-slate-500">Acompanhe gastos confirmados e pendentes.</p></div><div class="flex items-center gap-3"><span class="period-select">{{ $budgets->count() }} ativo(s)</span><button type="button" class="btn-primary" wire:click="$set('budgetModalOpen', true)">+ Novo orçamento</button></div></div><section class="card"><div class="space-y-4">@forelse($budgets as $budgetItem) @php($summary = $budgetSummaries[$budgetItem->id])<div><div class="flex justify-between gap-3"><div><b class="text-sm text-slate-700">{{ $budgetItem->category?->name ?? 'Todas as despesas' }}</b><small class="mt-0.5 block text-xs text-slate-400">Alerta em {{ $summary['threshold'] }}%</small></div><div class="text-right"><strong class="text-sm {{ $summary['status'] === 'exceeded' ? 'text-rose-600' : ($summary['status'] === 'warning' ? 'text-amber-600' : 'text-slate-800') }}">R$ {{ number_format($summary['spent'], 2, ',', '.') }}</strong><small class="block text-xs text-slate-400">de R$ {{ number_format($summary['amount'], 2, ',', '.') }}</small></div></div><div class="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><i class="block h-full rounded-full {{ $summary['status'] === 'exceeded' ? 'bg-rose-500' : ($summary['status'] === 'warning' ? 'bg-amber-400' : 'bg-emerald-400') }}" style="width: {{ min(100, $summary['percentage']) }}%"></i></div><div class="mt-1 flex justify-between text-xs text-slate-400"><span>{{ number_format($summary['percentage'], 0, ',', '.') }}% utilizado</span><span>{{ $summary['remaining'] >= 0 ? 'Restam R$ '.number_format($summary['remaining'], 2, ',', '.') : 'Excedeu R$ '.number_format(abs($summary['remaining']), 2, ',', '.') }}</span></div><button wire:click="archiveBudget({{ $budgetItem->id }})" wire:confirm="Arquivar este orçamento?" class="mt-1 text-xs text-slate-400 hover:text-rose-600">Arquivar</button></div>@empty<p class="empty-copy">Nenhum orçamento para este mês.</p>@endforelse</div></section></div>
        @else
            <div class="tab-panel"><div class="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-semibold text-slate-900">Minhas metas</h2><p class="mt-1 text-sm text-slate-500">Atualize o progresso conforme guardar dinheiro.</p></div><div class="flex items-center gap-3"><span class="period-select">{{ $goals->count() }} ativa(s)</span><button type="button" class="btn-primary" wire:click="$set('goalModalOpen', true)">+ Nova meta</button></div></div><section class="card"><div class="space-y-4">@forelse($goals as $goalItem) @php($summary = $goalSummaries[$goalItem->id])<div class="rounded-xl bg-stone-50 p-4"><div class="flex justify-between gap-3"><div><b class="text-sm text-slate-700">{{ $goalItem->name }}</b><small class="mt-0.5 block text-xs text-slate-400">{{ $goalItem->deadline ? 'Prazo: '.$goalItem->deadline->format('d/m/Y') : 'Sem prazo definido' }}</small></div><strong class="text-sm text-emerald-700">{{ number_format($summary['percentage'], 0, ',', '.') }}%</strong></div><div class="mt-2 h-2 overflow-hidden rounded-full bg-white"><i class="block h-full rounded-full bg-emerald-400" style="width: {{ $summary['percentage'] }}%"></i></div><div class="mt-1 flex justify-between text-xs text-slate-500"><span>R$ {{ number_format($summary['current'], 2, ',', '.') }}</span><span>Meta: R$ {{ number_format($summary['target'], 2, ',', '.') }}</span></div><div class="mt-3 flex items-end gap-2"><label class="field flex-1 text-xs">Adicionar valor<input wire:model="goalProgress.{{ $goalItem->id }}" type="number" step="0.01" min="0.01" placeholder="0,00"></label><button wire:click="addProgress({{ $goalItem->id }})" class="btn-secondary px-3 py-2">Adicionar</button><button wire:click="completeGoal({{ $goalItem->id }})" wire:confirm="Marcar esta meta como concluída?" class="text-xs text-slate-400">Concluir</button></div><button wire:click="deleteGoal({{ $goalItem->id }})" wire:confirm="Excluir esta meta?" class="mt-2 text-xs text-rose-500">Excluir meta</button></div>@empty<p class="empty-copy">Crie sua primeira meta financeira.</p>@endforelse</div></section></div>
        @endif
    </section>

    @if($budgetModalOpen)<div class="modal-backdrop" style="position:fixed;inset:0;z-index:99999;display:flex;align-items:center;justify-content:center;overflow-y:auto;background:rgba(15,23,42,.45);padding:1rem" wire:keydown.escape="$set('budgetModalOpen', false)" wire:click.self="$set('budgetModalOpen', false)"><div class="modal-card" role="dialog" aria-modal="true" aria-labelledby="budget-modal-title"><div class="modal-header"><div><h2 id="budget-modal-title" class="font-semibold">Novo orçamento</h2><p class="mt-1 text-xs text-slate-500">Defina quanto pode gastar no mês.</p></div><button type="button" class="modal-close" wire:click="$set('budgetModalOpen', false)" aria-label="Fechar">×</button></div><form wire:submit="saveBudget" class="space-y-4"><label class="field">Categoria<select wire:model="budget.category_id"><option value="">Todas as despesas</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select>@error('budget.category_id')<span class="form-error">Escolha uma categoria de despesa válida.</span>@enderror</label><div class="grid gap-4 sm:grid-cols-2"><label class="field">Mês<input wire:model="budget.month" type="month">@error('budget.month')<span class="form-error">Informe um mês válido.</span>@enderror</label><label class="field">Limite<input wire:model="budget.amount" type="number" step="0.01" placeholder="0,00">@error('budget.amount')<span class="form-error">Informe um limite maior que zero.</span>@enderror</label></div><label class="field">Alertar a partir de (%)<input wire:model="budget.alert_threshold" type="number" min="1" max="100"></label><label class="flex items-center gap-2 text-sm text-slate-600"><input wire:model="budget.is_recurring" type="checkbox" class="rounded border-slate-300 text-emerald-600 focus:ring-emerald-500"><span>Repetir mensalmente</span></label><p class="text-xs text-slate-400">Uma cópia será criada automaticamente nos próximos meses.</p><button class="btn-primary w-full">Criar orçamento</button></form></div></div>@endif

    @if($goalModalOpen)<div class="modal-backdrop" style="position:fixed;inset:0;z-index:99999;display:flex;align-items:center;justify-content:center;overflow-y:auto;background:rgba(15,23,42,.45);padding:1rem" wire:keydown.escape="$set('goalModalOpen', false)" wire:click.self="$set('goalModalOpen', false)"><div class="modal-card" role="dialog" aria-modal="true" aria-labelledby="goal-modal-title"><div class="modal-header"><div><h2 id="goal-modal-title" class="font-semibold">Nova meta financeira</h2><p class="mt-1 text-xs text-slate-500">Acompanhe uma reserva, viagem ou projeto.</p></div><button type="button" class="modal-close" wire:click="$set('goalModalOpen', false)" aria-label="Fechar">×</button></div><form wire:submit="saveGoal" class="space-y-4"><label class="field">Nome<input wire:model="goal.name" placeholder="Ex.: Reserva de emergência">@error('goal.name')<span class="form-error">Informe um nome para a meta.</span>@enderror</label><div class="grid gap-4 sm:grid-cols-2"><label class="field">Valor alvo<input wire:model="goal.target_amount" type="number" step="0.01" placeholder="0,00">@error('goal.target_amount')<span class="form-error">Informe um valor alvo maior que zero.</span>@enderror</label><label class="field">Já guardado<input wire:model="goal.current_amount" type="number" step="0.01" placeholder="0,00"></label></div><label class="field">Prazo<input wire:model="goal.deadline" type="date"></label><button class="btn-primary w-full">Criar meta</button></form></div></div>@endif

    <style>
        .modal-card { width: 100% !important; max-width: 32rem !important; max-height: calc(100vh - 2rem) !important; overflow-y: auto !important; background: #fff !important; border: 1px solid #e2e8f0 !important; border-radius: 1rem !important; padding: 1.5rem !important; box-shadow: 0 25px 50px -12px rgba(15, 23, 42, .28) !important; }
        .modal-header { display: flex !important; align-items: flex-start !important; justify-content: space-between !important; gap: 1rem !important; }
        .modal-close { margin-left: auto !important; display: grid !important; place-items: center !important; width: 2rem !important; height: 2rem !important; flex: 0 0 2rem !important; border: 0 !important; border-radius: .5rem !important; color: #dc2626 !important; background: transparent !important; font-size: 1.5rem !important; line-height: 1 !important; cursor: pointer !important; }
    </style>
</div>
